package com.laic.slider.api.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InclinometerCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    public InclinometerCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("TIME is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("TIME =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("TIME <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("TIME >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("TIME >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("TIME <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("TIME <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("TIME in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("TIME not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("TIME between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("TIME not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andAvalueIsNull() {
            addCriterion("AVALUE is null");
            return (Criteria) this;
        }

        public Criteria andAvalueIsNotNull() {
            addCriterion("AVALUE is not null");
            return (Criteria) this;
        }

        public Criteria andAvalueEqualTo(BigDecimal value) {
            addCriterion("AVALUE =", value, "avalue");
            return (Criteria) this;
        }

        public Criteria andAvalueNotEqualTo(BigDecimal value) {
            addCriterion("AVALUE <>", value, "avalue");
            return (Criteria) this;
        }

        public Criteria andAvalueGreaterThan(BigDecimal value) {
            addCriterion("AVALUE >", value, "avalue");
            return (Criteria) this;
        }

        public Criteria andAvalueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AVALUE >=", value, "avalue");
            return (Criteria) this;
        }

        public Criteria andAvalueLessThan(BigDecimal value) {
            addCriterion("AVALUE <", value, "avalue");
            return (Criteria) this;
        }

        public Criteria andAvalueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AVALUE <=", value, "avalue");
            return (Criteria) this;
        }

        public Criteria andAvalueIn(List<BigDecimal> values) {
            addCriterion("AVALUE in", values, "avalue");
            return (Criteria) this;
        }

        public Criteria andAvalueNotIn(List<BigDecimal> values) {
            addCriterion("AVALUE not in", values, "avalue");
            return (Criteria) this;
        }

        public Criteria andAvalueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AVALUE between", value1, value2, "avalue");
            return (Criteria) this;
        }

        public Criteria andAvalueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AVALUE not between", value1, value2, "avalue");
            return (Criteria) this;
        }

        public Criteria andBvalueIsNull() {
            addCriterion("BVALUE is null");
            return (Criteria) this;
        }

        public Criteria andBvalueIsNotNull() {
            addCriterion("BVALUE is not null");
            return (Criteria) this;
        }

        public Criteria andBvalueEqualTo(BigDecimal value) {
            addCriterion("BVALUE =", value, "bvalue");
            return (Criteria) this;
        }

        public Criteria andBvalueNotEqualTo(BigDecimal value) {
            addCriterion("BVALUE <>", value, "bvalue");
            return (Criteria) this;
        }

        public Criteria andBvalueGreaterThan(BigDecimal value) {
            addCriterion("BVALUE >", value, "bvalue");
            return (Criteria) this;
        }

        public Criteria andBvalueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BVALUE >=", value, "bvalue");
            return (Criteria) this;
        }

        public Criteria andBvalueLessThan(BigDecimal value) {
            addCriterion("BVALUE <", value, "bvalue");
            return (Criteria) this;
        }

        public Criteria andBvalueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BVALUE <=", value, "bvalue");
            return (Criteria) this;
        }

        public Criteria andBvalueIn(List<BigDecimal> values) {
            addCriterion("BVALUE in", values, "bvalue");
            return (Criteria) this;
        }

        public Criteria andBvalueNotIn(List<BigDecimal> values) {
            addCriterion("BVALUE not in", values, "bvalue");
            return (Criteria) this;
        }

        public Criteria andBvalueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BVALUE between", value1, value2, "bvalue");
            return (Criteria) this;
        }

        public Criteria andBvalueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BVALUE not between", value1, value2, "bvalue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}