package com.laic.slider.api.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Inclinometer extends BaseEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SD_BGK6150.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SD_BGK6150.TIME
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SD_BGK6150.AVALUE
     *
     * @mbggenerated
     */
    private BigDecimal avalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SD_BGK6150.BVALUE
     *
     * @mbggenerated
     */
    private BigDecimal bvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SD_BGK6150.CODE
     *
     * @return the value of T_SD_BGK6150.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SD_BGK6150.CODE
     *
     * @param code the value for T_SD_BGK6150.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SD_BGK6150.TIME
     *
     * @return the value of T_SD_BGK6150.TIME
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SD_BGK6150.TIME
     *
     * @param time the value for T_SD_BGK6150.TIME
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SD_BGK6150.AVALUE
     *
     * @return the value of T_SD_BGK6150.AVALUE
     *
     * @mbggenerated
     */
    public BigDecimal getAvalue() {
        return avalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SD_BGK6150.AVALUE
     *
     * @param avalue the value for T_SD_BGK6150.AVALUE
     *
     * @mbggenerated
     */
    public void setAvalue(BigDecimal avalue) {
        this.avalue = avalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SD_BGK6150.BVALUE
     *
     * @return the value of T_SD_BGK6150.BVALUE
     *
     * @mbggenerated
     */
    public BigDecimal getBvalue() {
        return bvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SD_BGK6150.BVALUE
     *
     * @param bvalue the value for T_SD_BGK6150.BVALUE
     *
     * @mbggenerated
     */
    public void setBvalue(BigDecimal bvalue) {
        this.bvalue = bvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Inclinometer other = (Inclinometer) that;
        return (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getAvalue() == null ? other.getAvalue() == null : this.getAvalue().equals(other.getAvalue()))
            && (this.getBvalue() == null ? other.getBvalue() == null : this.getBvalue().equals(other.getBvalue()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getAvalue() == null) ? 0 : getAvalue().hashCode());
        result = prime * result + ((getBvalue() == null) ? 0 : getBvalue().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", code=").append(code);
        sb.append(", time=").append(time);
        sb.append(", avalue=").append(avalue);
        sb.append(", bvalue=").append(bvalue);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}