package com.laic.slider.api.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Raingauge extends BaseEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SD_RAINGAUGE.TIME
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SD_RAINGAUGE.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SD_RAINGAUGE.RAINVALUE
     *
     * @mbggenerated
     */
    private BigDecimal rainvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SD_RAINGAUGE.TIME
     *
     * @return the value of T_SD_RAINGAUGE.TIME
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SD_RAINGAUGE.TIME
     *
     * @param time the value for T_SD_RAINGAUGE.TIME
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SD_RAINGAUGE.CODE
     *
     * @return the value of T_SD_RAINGAUGE.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SD_RAINGAUGE.CODE
     *
     * @param code the value for T_SD_RAINGAUGE.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SD_RAINGAUGE.RAINVALUE
     *
     * @return the value of T_SD_RAINGAUGE.RAINVALUE
     *
     * @mbggenerated
     */
    public BigDecimal getRainvalue() {
        return rainvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SD_RAINGAUGE.RAINVALUE
     *
     * @param rainvalue the value for T_SD_RAINGAUGE.RAINVALUE
     *
     * @mbggenerated
     */
    public void setRainvalue(BigDecimal rainvalue) {
        this.rainvalue = rainvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Raingauge other = (Raingauge) that;
        return (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getRainvalue() == null ? other.getRainvalue() == null : this.getRainvalue().equals(other.getRainvalue()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getRainvalue() == null) ? 0 : getRainvalue().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", time=").append(time);
        sb.append(", code=").append(code);
        sb.append(", rainvalue=").append(rainvalue);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}