package com.laic.slider.api.mapper;

import com.laic.slider.api.model.Humidistat;
import com.laic.slider.api.model.HumidistatCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface HumidistatMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_CAMPBELL229
     *
     * @mbggenerated
     */
    int countByExample(HumidistatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_CAMPBELL229
     *
     * @mbggenerated
     */
    int deleteByExample(HumidistatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_CAMPBELL229
     *
     * @mbggenerated
     */
    int insert(Humidistat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_CAMPBELL229
     *
     * @mbggenerated
     */
    int insertSelective(Humidistat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_CAMPBELL229
     *
     * @mbggenerated
     */
    List<Humidistat> selectByExampleWithRowbounds(HumidistatCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_CAMPBELL229
     *
     * @mbggenerated
     */
    List<Humidistat> selectByExample(HumidistatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_CAMPBELL229
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Humidistat record, @Param("example") HumidistatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_CAMPBELL229
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Humidistat record, @Param("example") HumidistatCriteria example);
}