package com.laic.slider.api.mapper;

import com.laic.slider.api.model.Inclinometer;
import com.laic.slider.api.model.InclinometerCriteria;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InclinometerMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    int countByExample(InclinometerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    int deleteByExample(InclinometerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("code") String code, @Param("time") Date time);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    int insert(Inclinometer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    int insertSelective(Inclinometer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    List<Inclinometer> selectByExampleWithRowbounds(InclinometerCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    List<Inclinometer> selectByExample(InclinometerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    Inclinometer selectByPrimaryKey(@Param("code") String code, @Param("time") Date time);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Inclinometer record, @Param("example") InclinometerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Inclinometer record, @Param("example") InclinometerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Inclinometer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_BGK6150
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Inclinometer record);
}