package com.laic.slider.api.mapper;

import com.laic.slider.api.model.Raingauge;
import com.laic.slider.api.model.RaingaugeCriteria;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RaingaugeMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    int countByExample(RaingaugeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    int deleteByExample(RaingaugeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("time") Date time, @Param("code") String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    int insert(Raingauge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    int insertSelective(Raingauge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    List<Raingauge> selectByExampleWithRowbounds(RaingaugeCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    List<Raingauge> selectByExample(RaingaugeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    Raingauge selectByPrimaryKey(@Param("time") Date time, @Param("code") String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Raingauge record, @Param("example") RaingaugeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Raingauge record, @Param("example") RaingaugeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Raingauge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SD_RAINGAUGE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Raingauge record);
}